=== Moonstroke/Xencha/src/main/xsd/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-FileCopyrightText: 2025 (c) Joachim MARIE <moonstroke+github@live.fr>
     SPDX-License-Identifier: MIT -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://moonstroke.github.io/xencha" xmlns:xencha="http://moonstroke.github.io/xencha" elementFormDefault="qualified">
	<element name="test" type="xencha:TestSuite">
		<annotation>
			<documentation>The test suite being defined.</documentation>
		</annotation>
	</element>
	<complexType name="TestSuite">
		<annotation>
			<documentation>The definition model of a test suite.</documentation>
		</annotation>
		<all>
			<element name="name" type="string" minOccurs="0">
				<annotation>
					<documentation>The name of the test suite.
					If not specified, the base name of the descriptor file will be used.</documentation>
				</annotation>
			</element>
			<element name="source" type="xencha:Source"/>
			<element name="cases">
				<complexType>
					<sequence>
						<element name="case" type="xencha:Case" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
		</all>
	</complexType>
	<complexType name="Source">
		<annotation>
			<documentation>A data component of tests.</documentation>
		</annotation>
		<choice>
			<element name="path" type="string"/>
			<element name="inline" type="xencha:InlineSource"/>
		</choice>
	</complexType>
	<complexType name="InlineSource" mixed="true">
		<sequence minOccurs="0">
			<any processContents="skip"/>
		</sequence>
	</complexType>
	<complexType name="Case">
		<annotation>
			<documentation>The definition of an elementary execution of the test.</documentation>
		</annotation>
		<all>
			<element name="input" type="xencha:Source"/>
			<element name="expectedOutput" type="xencha:Source"/>
		</all>
	</complexType>
</schema>

=== Moonstroke/Xencha/src/test/resources/source-path-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-FileCopyrightText: 2025 (c) Joachim MARIE <moonstroke+github@live.fr>
     SPDX-License-Identifier: MIT -->
<test xmlns="http://moonstroke.github.io/xencha" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://moonstroke.github.io/xencha ../../main/xsd/test.xsd">
	<name>Tests for external source</name>
	<source>
		<path>data/extract-playlist-duration.xsl</path>
	</source>
	<cases>
		<case>
			<name>Test for external source with external input/output</name>
			<input>
				<path>data/playlists.xml</path>
			</input>
			<expectedOutput>
				<path>data/playlist-durations.xml</path>
			</expectedOutput>
		</case>
		<case>
			<name>Test for external source with embedded input/output</name>
			<input>
				<inline>
					<!-- TODO -->
				</inline>
			</input>
			<expectedOutput>
				<inline>
					<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">
						<!-- TODO -->
					</fo:root>
				</inline>
			</expectedOutput>
		</case>
	</cases>
</test>
